spring:
  application:
    name: seleniumapp

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    rest:
      base-path: /api

  devtools:
    restart:
      enabled: false

okta:
  oauth2:
    issuer: https://dev-jmmbz1os1wlmcz3i.us.auth0.com/
    audience: https://example.com/
    client-id: MEcW60I2dYY94pdex5BPIuzvItDmJL3d
    client-secret: jgwI73SPbhIZ48F263_aVr8esvnMHa7O6Mt2pK34AbZ-FjyxopKtJ5X8gpnlMdS6
